# Generated by Django 2.1.2 on 2018-10-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
