# Generated by Django 2.1.2 on 2018-10-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vivienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='estado',
        ),
        migrations.AddField(
            model_name='perro',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disopnible'), (2, 'no')], default=2),
        ),
    ]
