# Generated by Django 2.1.2 on 2018-10-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181028_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='est',
            new_name='estado',
        ),
        migrations.AddField(
            model_name='perro',
            name='foto',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='core/img/'),
        ),
    ]
