# Generated by Django 2.1.2 on 2018-10-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181028_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(upload_to='media', verbose_name='Imágen'),
        ),
    ]
