# Generated by Django 2.1.2 on 2018-10-30 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181029_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptante',
            old_name='fecha',
            new_name='edad',
        ),
        migrations.AddField(
            model_name='adoptante',
            name='perro',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='core.Perro'),
        ),
    ]
