# Generated by Django 2.1.2 on 2018-10-30 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181030_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptante',
            name='vivienda',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='core.Vivienda'),
        ),
    ]
